# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f980bd4103ba632cb683f883f45611320e31d13e14783c666fc129a47f3b8bb0102f46c2de9a757f3c497671f1f2fc29dc4382ffe499c58a913fea4adea282df

test:
  secret_key_base: b0885a608e423c3ae29a54b3206ea6a46bfa3eac73737aa76014896b7278886c6ecb4536e8f9d1a347fd8e94fd965d1efb29dc5a795714b865eda498cc2065b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
